apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    "signingSecret": "AgBaeKaXnn93QBlecoGcGcSJi5mKbGf7yq7/w35zgq8DK9wDKfxQJ6zI+YQkSUDEQRxzQFcI1yRD6JooU/MNe2acBFZvOByKkpWTDqc3xgvY8zcM4Ojwe4gxxlAEQ+chW8MY/A4mzLhq9hbgu0KvAeMKPWPdhkOpLV7VosBW5tu/dPrPJBDRQzwEyu8STl+1X+gVffriB1gXrasAh91j/50ETrYymI7vZouP/plxhGYlo86d4OuE+mrrd8U2JSQsHE5FryBXITy+dVTw8owkFgpb3uWSql6opT+oo1X2EW2p8lfmLSJ8nFm1ogjys6nYZjxab6yFrlzHeTJbKEPn3EXgE7zIjNjYLeltf8C9YNuxQSSruuCur8ryJPdYA7gfaQNWXf1G1f0hYvx1/mvUsMVijMgaPtuoscGcNseXrr2lu8q+COJXSkveHIVTH0CWxzlvc4/QyntvtXJ6RdsM7dlVH6poYnhcIOi41uiPd+uAHUv1b1S3ZntzjFwnZfZzLmQpfE8ouTXnXLtGAHupE97pSwtb/WdiRRuJIK1y+KpoHUI9vmww1QXrgYB/E3Ln/G3m0H+uWjP1yXHRU5oi/CWoHI3DwG6IV35Os8gWuUBEAyRZqxihbggNgQno32WBl6WqWtxA4j6SxG5hzqH2SvH8LYasbuNBWaGuLBK0U1cEw5p01mFc+5PlusRPJ18Z+95Da3svvXP3"
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
    type: Opaque
