---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    signingSecret: AgAZn3tTIZ9LZ/BNRiCt7bzZSO/DfL3zUNbKw6DU6nfs/rrC2CRZUbnqDacv24Y7JZYILuZFCjAkySjz53OEl+eH9MqPT3wGypnIJUDASugUijGnUEGVrd9DSe3VziC3BJ6sUqcC9HqPJNn2jX/wTvOh/zAIJUyIr49R5dXoUqEXp3oTQ9SBSZWIYHckNRfQFqH6oxcVIGpHHwHipj9o54l3oMGdf3oIdWd7jGT/LLCO9NyzlymQ4HTD1gRzUKQX68R5LHXdUgDYsE2X8VmwPfKRpIiY5LeASqg7xRybVlE9/KDmYwwbeaLUzN3QjMzVdzehNFiwke0U5a0ZGjsh4ilkdPKeXsRdMVrj01s40d3nSIMef1meEzyiQ0y2DYaAsKZkHxLOsHAEYJSgg6m0kAbBZVMf8r08bX9K/rGBNYOGj++ZN8wR8vSVcHmfrL+s6SSCLpUyGoaHx/wcyd/S4lL/fHRmcP/ztmzyfPhTXtiL+iNCIjnRgJc1+LpdwsIANsw+jbl2ENO1C3C0W+ZU7KYBU40VEFViOCcmuFmrfgb9AH5OF3P4yBKxumnjeef/a84G9R4cvSzamMYhSHXvndOsokBota1gsueINLaMynTpMWO+hc6oV/mRzF9SCg7d9f3iovN9BXs/3ZG+sJEf1emd5/fMoT8D79pi4+Rd0t8IwldUbYxcSPcYgFTADIpGklHmVSXzgcLF
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
    type: Opaque
