apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised  #automated update of the primary once all
  #                 replicas have been upgraded (default)
  storage:
    size: 1Gi