apiVersion: v1
kind: Pod
metadata:
  name: back-pod
  labels:
    component: back
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  containers:
  - name: backend
    image: dhairyarora0208/streamhard-backend
    ports:
      - name: backend-port
        containerPort: 8000
    env:
      - name: SIGNINGSECRET
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: signingSecret
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password
    envFrom:
      - configMapRef:
          name: backend-config