apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    component: db
spec:
  containers:
    - name: pg
      image: postgres:alpine
      env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: PASSWORD
      ports:
        - containerPort: 5432