apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  # name: media-plane
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    component: back
  ports:
    - port: 80
      targetPort: 8000